config/routes.rb
Rails.application.routes.draw do

  root "articles#index"

  resources :users, only: [:new, :create] 
  
  get 'login', to: 'sessions#new' 
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'sessions', to: 'sessions#destroy'

  get 'authorized', to: 'sessions#page_requires_login'

  get "/articles/process", to:"articles#processData"
  resources :articles
#  get "/articles", to: "articles#index"
#  get "/articles/:id", to: "articles#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
    
    def self.processData(article_id,action)
        return []  unless ["activate", "deactive"].include?(action)
        Article.send(action, article_id)
    end

    def self.activate(article_id)
        puts "activate the status of #{article_id}"
    end

    def self.deactive(article_id)
        puts "activate the status of #{article_id}"
    end 

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #  protect_from_forgery with: :exception

    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?

    def current_user        
        User.find_by(id: session[:user_id])  
    end

    def logged_in?
        !current_user.nil? 
    end

    def authorized   
        redirect_to '/welcome' unless logged_in?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
#include ArcticleProssess

  #skip_before_action :verify_authenticity_token

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def processData
    Article.processData(params[:id],params[:nextAction])
    @article = Article.find(params[:id])
    redirect_to @article
  end 

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]
  skip_before_action :verify_authenticity_token, only: [:new, :create, :welcome]

  def new
  end

  def login
  end

  def create  
     @user = User.find_by(username: params[:username])   
     if @user && @user.authenticate(params[:password])     
       session[:user_id] = @user.id      
       redirect_to '/welcome'
      else     
         redirect_to '/login'  
      end
  end

  def page_requires_login
  end

  def destroy
    session.clear
    redirect_to '/login'
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [ :new, :create]

  def new   
    @user = User.new
  end

  def create  
      @user = User.create(params.require(:user).permit(:username,:password))  
      session[:user_id] = @user.id  
      redirect_to "/welcome"
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def activate(article_title)
        print 'activate the status of #{article_title}'
    end

    def deactive(article_title)
        print 'activate the status of #{article_title}'
    end 

    def processData(article_id,action)
        self.send(action, article_id)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actions/index.html.erb
<h1>Actions#index</h1>
<p>Find me in app/views/actions/index.html.erb</p>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
      <ul>
      <li><%= link_to "Activate", "/articles/process?id=1&nextAction=activate" %></li>
      <li><%= link_to "Deactivate", "/articles/process?id=1&nextAction=deactivate" %></li>
      </ul>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>
<div>
<%=link_to 'Log Out', sessions_path, method: :delete%>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBenchmark</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%> 
    <%= f.label :username%><br> 
    <%= f.text_field :username%><br> 
    <%= f.label :password%><br> 
    <%= f.password_field :password%><br> 
    <%= f.submit %><%end%>